### ISSUE TITLE
HTML Canvas rendered flip vertically 

### ISSUE THREAD

**Issue by vasanthudhaya** [AlexVestin/WasmVideoEncoder#2]
Hi, @AlexVestin Thanks for this repo. 

I drawed a video element in canvas and called the getImageData() then sent the image Data to video encoder, but the video output i got it is flipped vertically.

Kindly let know me if there any way to resolve this issue. That will be very helpful for me.  For Your reference i paste the code below

```
var canvas = document.createElement('canvas');
var ctx  = canvas.getContext('2d');
ctx.drawImage(videoElement, 0, 0, 800, 800);
const ctxData2 = ctx.getImageData(0, 0, 800, 800);
var pixels2 = ctxData2.data;
worker.sendFrame(pixels2);
```

Original video image: 

![image](https://user-images.githubusercontent.com/51599349/70709853-e9a16f80-1d03-11ea-9f29-5cbb35dbfc3a.png)

Rendered video image : 

![image](https://user-images.githubusercontent.com/51599349/70709757-ad6e0f00-1d03-11ea-8d43-9e82fda75d5e.png)

**Comment by AlexVestin** [comment]
This build was targetting the WebGL version which has the drawbuffer flipped,  
https://github.com/AlexVestin/WasmVideoEncoder/blob/master/webassembly/C/avio_write.c#L188

would probably be a good idea to have have to toggle this from the js side

**Comment by vasanthudhaya** [comment]
Thanks for your valuable time @AlexVestin. Is there any way to remove the flip-code without a new build.

**Comment by vasanthudhaya** [comment]
Hi @AlexVestin ,

I have tried a lot in js side to toggle the flip-vertical method. But wont works for me. 

1. So, am removed the flip vertical code in c file. Then i compiled the steps which you have gave in readmefile.md without ECMAScript method. But not reflected in js file and wasm file. 

**Build method which i used :**

```
git clone https://github.com/AlexVestin/WasmVideoEncoder.git
cd WasmVideoEncoder
git submodule init
git submodule update --recursive
```
> (https://github.com/AlexVestin/WasmVideoEncoder#to-run-tests-without-emscripten)


```
cd build/reg
make 
cd ../../C
LD_LIBRARY_PATH=/WasmVideoEncoder/webassembly/build/reg/lib
PKG_CONFIG_PATH=/WasmVideoEncoder/webassembly/build/reg/lib/pkgconfig
export LD_LIBRARY_PATH
export PKG_CONFIG_PATH
make [your test]
```

2. Kindly know how to rebuild the js file and wasm file using without ECMAScript and explain the method how to recreate properly the files, that will be very useful for me. Thanks in advance

**Comment by AlexVestin** [comment]
There isn't currently a way to turn this off from javascript currently, sorry. The Emscripten build is what will generate the WebAssembly, so you'll need to use that one if you want to use it on the web (Emscripten != ECMAScript, but I can see the confusion). 

Here's the link for Emscripten: https://emscripten.org/docs/getting_started/downloads.html
Note that I'm unsure if this will build on Windows without modifications, but you could use Linux Subsystems (If you're using windows).

I'd recommend simply rotating the image in Javascript in the meantime though, 
Here is a couple of ways you can do that: 
https://stackoverflow.com/a/41973289/3442097

**Comment by vasanthudhaya** [comment]
Very thankful to you @AlexVestin , Now the video flip vertical issue has been resolved.
