### ISSUE TITLE
output file size larger 

### ISSUE THREAD

**Issue by vasanthudhaya** [AlexVestin/WasmVideoEncoder#3]
Hi @AlexVestin, When am encoding the 3 minute video with 1080px and 24fps, the output video size becomes large ie: 276MB

Kindly let me know how to minimize the encode file size. That will be very useful for me. 

Thanks in advance.

**Comment by AlexVestin** [comment]
Lowering the bitrate and setting an appropriate preset helps (utlrafast provides larger files, but faster encoding).
The file sizes in the benchmark are misleading, they used the demo cube (which is easy to encode), and should only be used to compared the different settings, not as a reference.

**Comment by vasanthudhaya** [comment]
Hi @AlexVestin Thanks for your reply... 

I have one more doubt, Sorry for asking this without try

I used only videoencoder.js for encode the video, but i need to know how the decoder.js works, So help me for that.  whether the decoder.js decode the video framebyframe or not.. If possible means kindly provide a demo website for how to use the code..

**Comment by AlexVestin** [comment]
You can find an example implementation here: https://github.com/AlexVestin/musicvid.org/blob/master/src/editor/animation/materials/OldVideoMaterial.js 

This is however a hybrid that uses an HTML video-element when not exporting, so you can ignore some of the code in there. 
Just a warning, the video decoding is a bit less developed so it might not work fully
