### ISSUE TITLE
How to add custom parameter to FFMPEG

### ISSUE THREAD

**Issue by Smithangshu** [AlexVestin/WasmVideoEncoder#7]
Hi, 

First of all, thank you for the awesome library. It works almost how I want for my case.
Only issue I am facing is if width or height is not multiple of 2 then it throws error in initialization. So I know I can send "scale='bitand(oh*dar,65534)':'min(720,ih)'" option then it will get fixed but the issue is I am unable to understand how I will be able to do it.

Please help me!

**Comment by AlexVestin** [comment]
Is that a command-line argument for FFmpeg?

**Comment by Smithangshu** [comment]
Yes right. Its a filter option.

**Comment by AlexVestin** [comment]
Okay! This project is using the C api and not the binary, so I don't think it's possible to simply pass it a scale/filter string, and I wouldn't really know how to implement it. If you want to use something similar to the CLI you should check out ffmpeg.js

**Comment by Smithangshu** [comment]
Well no problem! But is it possible to feed the encoder with pixel data directly from 2d canvas instead of WebGL/Three.js canvas by using something like context.getImageData() or canvas.toDataURL()? 
Please suggest.

**Comment by AlexVestin** [comment]
Yeah, you can check out #2 for more info

**Comment by Smithangshu** [comment]
Excellent! One thing I must say this is the best optimized ffmpeg based encoder in js. It's extremely fast even in mobile with very good quality. But sadly I am facing another issue like if I am sending 20 frame for 4 seconds video then a strange thing is happening it encodes 1...10 frames upto 2000 ms then from 2001 ms it goes to 10...1 instead of going 11...20. I am not getting what might cause the issue. 
Can you please help me on this?

**Comment by AlexVestin** [comment]
Like it's sending the same image sequence, but backwards? Do you haven an example?
